openapi: 3.0.0
info:
  title: 1447.tbcv_sofk-commonApi-s-rest-v1
  version: 1.0.0
  description: Методы и модели для работы с API СОФК
servers:
  - url: https://vip-prime-sofk.apps.ds1-genr01.corp.dev.vtb/v1
    description: DSO
  - url: https://vip-prime-sofk.k3-vip-prime.apps.ss1-genr01.test.vtb.ru/v1
    description: K3
  - url: https://vip-prime-sofk.k4-vip-prime.apps.ss1-genr01.test.vtb.ru/v1
    description: K4
  - url: https://vip-prime-sofk.tbcv.region.vtb.ru/v1
    description: PROD
tags:
  - name: check-personal-managers-controller
    description: Методы работы с персональными менеджерами
paths:
  /ext/check/personalManager:
    post:
      description: Проверить возможности получения данных в карточке сотрудника
      operationId: check_personal_manager
      tags:
        - check-personal-managers-controller
      parameters:
        - name: Initiator-Service
          in: header
          required: false
          description: Имя сервиса запрашивающий данные
          schema:
            type: string
            maxLength: 20
      requestBody:
        description: Параметры запроса метода
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckPmRequestParams'
      responses:
        "200":
          description: Основной и замещающий менеджер
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckPmResult'
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
        "404":
          description: Клиент не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
        "422":
          description: Команда обслуживания не назначена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
components:
  schemas:
    CheckPmRequestParams:
      type: object
      description: Параметры запроса проверки данных ПМ
      additionalProperties: false
      required:
        - login
        - mdm_id
      properties:
        login:
          type: string
          minLength: 1
          maxLength: 50
          description: Логин сотрудника пытающийся открыть карточку клиента
          example: login1
        mdm_id:
          type: string
          minLength: 1
          maxLength: 40
          description: MDM ID клиента
          example: '159666324'
    CheckPmResult:
      type: object
      description: Ответ метода проверки данных ПМ
      additionalProperties: false
      required:
        - isAllowed
      properties:
        isAllowed:
          type: boolean
          description: Признак того, что сотрудник и клиент находятся в одной точке продаж
          example: false
    SofkErrorDto:
      type: object
      description: Ошибки при выполнении запроса
      additionalProperties: false
      properties:
        time:
          type: string
          format: 'date-time'
          description: Время ответа
          
        status:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
          description: Код ответа
        error:
          type: string
          maxLength: 255
          description: Причина ошибки
        message:
          type: string
          maxLength: 255
          description: Сообщение ошибки
        path:
          type: string
          description: URN ответа
          maxLength: 100
          example: /employee/by-login/12342123