openapi: 3.0.0
info:
  title: 1447.tbcv_historyUiApi-s-rest-v1
  version: 1.0.0
  description: Методы для вызова с UI сервиса history
servers:
  - url: https://vip-prime-history.apps.ds1-genr01.corp.dev.vtb/v1
    description: DSO
  - url: https://vip-prime-history.k3-vip-prime.apps.ss1-genr01.test.vtb.ru/v1
    description: K3
  - url: https://vip-prime-history.k4-vip-prime.apps.ss1-genr01.test.vtb.ru/v1
    description: K4
  - url: https://vip-prime-history.tbcv.region.vtb.ru/v1
    description: PROD
tags:
  - name: service-team-history-controller
    description: Методы для работы с историей изменений клиента в МС history
  - name: client-team-history-controller
    description: Методы для работы с историей изменений клиента в МС history
paths:
  /int/serviceteam/supervip/history/list:
    post:
      tags:
        - service-team-history-controller
      description: >-
        История изменений в команде обслуживания клиента для экрана
        администратора супервип
      operationId: service_team_supervip_history
      requestBody:
        description: Параметры запроса списка
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTeamHistoryRequestParams'
      responses:
        '200':
          description: История изменений в команде обслуживания
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTeamHistoryEventList'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
        '401':
          description: Проблема с аутентификацией пользователя
          content: {}
        '500':
          description: Неизвестная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
  /int/serviceteam/client/history/list:
    post:
      tags:
        - service-team-history-controller
      description: >-
        История изменений в команде обслуживания клиента для всех экранов кроме экрана администратора SuperVip
      operationId: service-team-history-controller
      requestBody:
        description: Параметры запроса списка
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTeamHistoryRequestParams'
      responses:
        '200':
          description: История изменений в команде обслуживания
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTeamHistoryEventList'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
        '401':
          description: Проблема с аутентификацией пользователя
          content: {}
        '500':
          description: Неизвестная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
  /int/client/serviceteam/history/list:
    post:
      tags:
        - client-team-history-controller
      description: >-
        История изменений в команде обслуживания для экрана КРО, запрос строится на основе mdmId, а не customerId
      operationId: client_service_team_history
      requestBody:
        description: Параметры запроса списка
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientServiceTeamHistoryRequestParams'
      responses:
        '200':
          description: История изменений в команде обслуживания
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTeamHistoryEventList'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
        '401':
          description: Проблема с аутентификацией пользователя
          content: {}
        '500':
          description: Неизвестная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SofkErrorDto'
components:
  schemas:
    ServiceTeamHistoryRequestParams:
      type: object
      description: Параметры запроса списка истории
      required:
        - customerId
        - page
        - pageSize
      additionalProperties: false
      properties:
        customerId:
          type: integer
          format: int64
          minimum: 1
          maximum: 9223372036854775807
        page:
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
        pageSize:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
        sortRules:
          type: array
          maxItems: 2147483647
          items:
            $ref: '#/components/schemas/FieldSortRule'
    ClientServiceTeamHistoryRequestParams:
      type: object
      description: Параметры запроса списка истории
      required:
        - mdmId
        - page
        - pageSize
      additionalProperties: false
      properties:
        mdmId:
          type: string
          maxLength: 50
          example: 1234567890
        page:
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
        pageSize:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
        sortRules:
          type: array
          maxItems: 2147483647
          items:
            $ref: '#/components/schemas/FieldSortRule'
    FieldSortRule:
      type: object
      description: Правило сортировки одного поля
      required:
        - fieldName
      additionalProperties: false
      properties:
        fieldName:
          type: string
          maxLength: 50
        direction:
          type: string
          enum:
            - asc
            - desc
    ServiceTeamHistoryEventList:
      type: object
      description: >-
        Информация для отображения экрана истории изменений в команде
        обслуживания клиента
      required:
        - list
      additionalProperties: false
      properties:
        list:
          type: array
          description: история изменений в команде обслуживания клиента
          maxItems: 2147483647
          items:
            $ref: '#/components/schemas/ClientServiceTeamHistoryEvent'
        aggregates:
          $ref: '#/components/schemas/ListAggregates'
    ClientServiceTeamHistoryEvent:
      type: object
      description: Запись об изменении в команде обслуживания клиента
      required:
        - datetime
        - type
        - comment
      additionalProperties: false
      properties:
        datetime:
          type: string
          format: date-time
          description: Дата
          pattern: >-
            ^[0-9]{4}-((0[1-9])|(1[0-2]))-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}(()|(.[0-9]{1,6})(Z|([+-](0[0-9]|1[0-2]):([0-5][0-9])))|(.[0-9]{1,6}))|)$
        type:
          type: string
          maxLength: 100
        comment:
          type: array
          maxItems: 2147483647
          items:
            $ref: '#/components/schemas/Pair'
        requester:
          type: object
          additionalProperties: false
          properties:
            employee:
              $ref: '#/components/schemas/Employee'
            branch:
              $ref: '#/components/schemas/Branch'
    ListAggregates:
      type: object
      description: Тотал данные о сформированном списке
      required:
        - total
      additionalProperties: false
      properties:
        total:
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
        sortableFields:
          type: array
          maxItems: 2147483647
          items:
            type: string
            maxLength: 50
    Pair:
      type: object
      description: Пара "Имя" - "Значение"
      required:
        - name
        - value
      additionalProperties: false
      properties:
        name:
          type: string
          description: Имя параметра
          maxLength: 100
        value:
          type: string
          description: Значение параметра
          maxLength: 255
    Employee:
      type: object
      description: Описание одного сотрудника
      additionalProperties: false
      required:
        - lastName
        - firstName
        - middleName
      properties:
        lastName:
          type: string
          maxLength: 50
        firstName:
          type: string
          maxLength: 50
        middleName:
          type: string
          maxLength: 50
        phoneNum:
          type: string
          maxLength: 40
        workPhoneNum:
          type: string
          maxLength: 40
        workPhoneExt:
          type: string
          maxLength: 20
    Branch:
      type: object
      description: Отделение
      additionalProperties: false
      properties:
        code:
          type: string
          maxLength: 50
        name:
          type: string
          maxLength: 100
    SofkErrorDto:
      type: object
      description: Ошибки при выполнении запроса
      additionalProperties: false
      properties:
        time:
          type: string
          format: date-time
          description: Время ответа
          pattern: >-
            ^[0-9]{4}-((0[1-9])|(1[0-2]))-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}(()|(.[0-9]{1,6})(Z|([+-](0[0-9]|1[0-2]):([0-5][0-9])))|(.[0-9]{1,6}))|)$
        status:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
          description: Код ответа
        error:
          type: string
          maxLength: 255
          description: Причина ошибки
        message:
          type: string
          maxLength: 255
          description: Сообщение ошибки
        path:
          type: string
          description: URN ответа
          maxLength: 100
          example: /employee/by-login/12342123